export default {
  "title": "HIIT - High Intensity Interval Training",
  "editRecord": "Edit",
  "createRecord": "New Workout",
  "back": "Back",
  "notFound": "Not Found",
  "filter": "Filter",
  "all": "All",
  "sort": "Sort",
  "newestFirst": "New to Old",
  "oldestFirst": "Old to New",
  "save": "Save",
  "delete": "Delete",
  "textRequired": "Text is required",
  "noRecords": "No workout history is available. Click the button above to begin a workout.",
  "recordCount": "{0} {1} total",
  "record": "workout",
  "records": "workouts",
};